controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_admin_dashboard_index:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
